### ISSUE TITLE
modify calculator popup to a "setup" popup

### ISSUE THREAD

**Issue by seiyria** [seiyria/root#16]
it should have (as separate tabs):

- calculator
- expanded calculator functionality ([pics here](https://boardgamegeek.com/image/4667593/walterbarrett))
  - whitelist - select or deselect factions to make sure they're in the list
  - blacklist - ignore chosen factions
  - show running reach total with current selected factions
  - show reach of each faction like presently
  - player count selector
- map randomizer

might want to get meeple pics too, to upgrade the calculator

`@guerrics` was interested in this the most.
![cult](https://user-images.githubusercontent.com/763609/83174842-9cae2b80-a0e0-11ea-9ce1-f233562c2e39.png)
![conspiracy](https://user-images.githubusercontent.com/763609/83174843-9d46c200-a0e0-11ea-9600-c97c78ff8087.png)
![duchy](https://user-images.githubusercontent.com/763609/83174846-9d46c200-a0e0-11ea-9ccf-34bc38669767.png)
![marquise](https://user-images.githubusercontent.com/763609/83174848-9d46c200-a0e0-11ea-80be-1d11686fdcef.png)
![eyrie](https://user-images.githubusercontent.com/763609/83174849-9ddf5880-a0e0-11ea-9740-aef8fb6478ae.png)
![woodland](https://user-images.githubusercontent.com/763609/83174854-9ddf5880-a0e0-11ea-88ba-6cde875b15f7.png)
![vagabond1](https://user-images.githubusercontent.com/763609/83174855-9ddf5880-a0e0-11ea-950d-5d637b3a49ac.png)
![vagabond2](https://user-images.githubusercontent.com/763609/83174856-9ddf5880-a0e0-11ea-938c-ebdd9eea9469.png)
![riverfolk](https://user-images.githubusercontent.com/763609/83174857-9e77ef00-a0e0-11ea-9ddc-9bceec9cef83.png)

**Comment by GuerricS** [comment]
Ha! I was very confused for a moment why and how you had emailed me about this before I realized the email was from Github

**Comment by seiyria** [comment]
Sorry about that! I generally try not to ping people (hence why I edited it). Didn't realize you had a github that matched that id!

**Comment by GuerricS** [comment]
No worries! I simply found it funny, especially because I only made this account yesterday
