### ISSUE TITLE
+1 draft for faction randomizer

### ISSUE THREAD

**Issue by seiyria** [seiyria/root#17]
fan-made.

- first, draft # players (named player 1-x for now) - turn order and draft order are reversed
- second:
  - first in turn order selects map (autumn, winter, lake, mountain)
  - second selects deck (E&P or original) 
- third, draw factions equal to the number of players that consider VB 2 correctly (basically, it can only be drawn if VB 1 is drawn) plus have a reach of at least 17, and then draw another random faction on top of that
- players can sort out the actual logistics, the UI just needs to be provided to do the simpler stuff like picking randomly

**Comment by mangofeet** [comment]
It would be good to integrate the map generator you currently have since the map generation is done before the factions are selected
